env: standard
runtime: nodejs14 # or another supported version
service: xtracts-label-maker

instance_class: F2

env_variables:
  REACT_APP_STRAPI_AUTH: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODE1ZjlkZmMzODA0M2Y0ODZkODM5YiIsImlhdCI6MTYyNDE5NTMzNCwiZXhwIjoxNjI2Nzg3MzM0fQ.C595IKD2f6OpsKTUxPMRGFlXZ12zUaHrX6vy-10Z6yA"

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    static_files: build/index.html
    upload: build/index.html
